### ISSUE TITLE
Invalid API Key when running with Mouser API

### ISSUE THREAD

**Issue by Kampi** [set-soft/kicost_ci_test#1]
I get the following output when running the demo with an Mouser API key

```
Progress:   0%|          | 0/12 [00:00<?, ?part/s]
Progress:   0%|          | 0/12 [00:00<?, ?part/s]
ERROR:Trace stack: (kibot.gs - gs.py:870)
  File "/usr/local/lib/python3.11/dist-packages/kibot/bom/xlsx_writer.py", line 732, in create_kicost_sheet
    return _create_kicost_sheet(workbook, groups, image_data, fmt_title, fmt_info, fmt_subtitle, fmt_head, fmt_cols, cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kibot/bom/xlsx_writer.py", line 687, in _create_kicost_sheet
    query_part_info(parts, dist_list)
  File "/usr/local/lib/python3.11/dist-packages/kicost/kicost.py", line 76, in query_part_info
    get_dist_parts_info(parts, dist_list, currency)
  File "/usr/local/lib/python3.11/dist-packages/kicost/distributors/__init__.py", line 50, in get_dist_parts_info
    distributor_class.get_dist_parts_info(parts, dist_list, currency)
  File "/usr/local/lib/python3.11/dist-packages/kicost/distributors/distributor.py", line 166, in get_dist_parts_info
    solved = api.query_part_info(parts, list(remaining), currency)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kicost/distributors/api_mouser.py", line 380, in query_part_info
    raise KiCostError(msg, ERR_SCRAPE)
ERROR:KiCost error: `Invalid unique identifier. (Invalid API Key)` (5) (kibot.gs - gs.py:884)
```

My API key looks like this

![image](https://github.com/user-attachments/assets/58d750a3-930c-4eb1-8cdc-4bf1ba318f46)

**Comment by set-soft** [comment]
Please take a look at the logs, they are stored even on fail.
I updated my Nexar secrets and successfully run the workflow.
The keys are obfuscated in the log file , if you take a look at the logs here you'll see:

```
DEBUG:Overwriting Mouser.key = dXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXe (kibot.kicost.dist - distributor.py:285)
```

This shows just the first and the last digits for the key, verify they are correct.

**Comment by Kampi** [comment]
> Please take a look at the logs, they are stored even on fail. I updated my Nexar secrets and successfully run the workflow. The keys are obfuscated in the log file , if you take a look at the logs here you'll see:
> 
> ```
> DEBUG:Overwriting Mouser.key = dXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXe (kibot.kicost.dist - distributor.py:285)
> ```
> 
> This shows just the first and the last digits for the key, verify they are correct.

Looks correct

```
DEBUG:  - language: EN (kibot.kicost - config.py:151)
DEBUG:Overwriting Mouser.key = 4XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX6 (kibot.kicost.dist - distributor.py:285)
DEBUG:Overwriting Element14.key =  (kibot.kicost.dist - distributor.py:285)
```

Is there an option to remove the obfuscation? Am I using the wrong API key? I´m using the ordering and cart API, but Mouser uses a different key for the search API, including prices, etc.

**Comment by Kampi** [comment]
> Please take a look at the logs, they are stored even on fail. I updated my Nexar secrets and successfully run the workflow. The keys are obfuscated in the log file , if you take a look at the logs here you'll see:
> 
> ```
> DEBUG:Overwriting Mouser.key = dXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXe (kibot.kicost.dist - distributor.py:285)
> ```
> 
> This shows just the first and the last digits for the key, verify they are correct.

I used the wrong API key. The pipeline is executed successfully with the search API key. You need this key:

https://www.mouser.de/api-search/
